# Generated by Django 2.1.7 on 2020-01-07 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ShoppingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('des', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('pro_image', models.ImageField(null=True, upload_to='productimage')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ShoppingApp.UserProfile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seller.Category')),
            ],
        ),
    ]
